### ISSUE TITLE
Update supported networks to include Goerli

### ISSUE THREAD

**Issue by willianpaixao** [graphprotocol/docs#172]
Follow up from https://github.com/graphprotocol/contracts/issues/587, the documentation needs to be updated with the new network and contract information.

**Comment by azf20** [comment]
thanks @willianpaixao - @tmigone let's leave this open to update when the new testnet protocol is ready

**Comment by tmigone** [comment]
Yes thanks for the notice. The other issue closed automatically and the testnet is not quite running, but will soon.

**Comment by Web3Slimchance** [comment]
Thank you for creating an issue. This was updated in #185
