### ISSUE TITLE
yarn global add @graphprotocol/graph-cli Not working

### ISSUE THREAD

**Issue by umershaikh123** [graphprotocol/docs#182]
as mentioned when I first try to install it with yarn and checked using graph -v  it was giving an error but when I use npm it worked
```
yarn global add @graphprotocol/graph-cli 
is not working 
```
 <br>

```
npm install -g @graphprotocol/graph-cli
is working
```

**Comment by Web3Slimchance** [comment]
I was not able to replicate this 🙏 
Make sure you add the yarn global binary path to the PATH environment variable.
