### ISSUE TITLE
one-to-many (Reverse Lookups)

### ISSUE THREAD

**Issue by autsada** [graphprotocol/docs#229]
I am learning how to build subgraphs and reading through the docs,  and quite confusing the second paragraph on the one-to-many reverse lookups topic which is 

_"For one-to-many relationships, the relationship should always be stored on the 'one' side, and the 'many' side should always be derived."_

Should it be the other way around? As the given example below, a **Token** can have many **TokenBalance**s, while a **TokenBalance** can belong to a single **Token**, so the 'one' side (Token) is "derived", and the 'many' side (TokenBalance) stores the relationship. 
```
type Token @entity(immutable: true) {
  id: Bytes!
  tokenBalances: [TokenBalance!]! @derivedFrom(field: "token")
}

type TokenBalance @entity {
  id: Bytes!
  amount: Int!
  token: Token!
}
```

**Comment by azf20** [comment]
thanks @autsada! I think in this case it's saying that the derived field is on the `one` side, so the `many` side can be derived from that. But I agree that the wording isn't clear. Do you have a wording in mind that you think would be clearer?

**Comment by autsada** [comment]
Thanks @azf20 for the clarification, I revisited the docs, and yes you are right, your explanation is clear enough.
Thank you for your time.
