### ISSUE TITLE
bring back path aliases

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/docs#320]
I agree, if you find a way to make it pass `pnpm lint`, let's put it back!

_Originally posted by @benface in https://github.com/graphprotocol/docs/pull/319#discussion_r1139569420_

**Comment by benface** [comment]
Well, already done in https://github.com/graphprotocol/docs/pull/319/commits/e8baaf649f0933da1b572dfba25ce2fe0aab29fe. :)
