### ISSUE TITLE
Is there solana support yet?

### ISSUE THREAD

**Issue by sherodtaylor** [graphprotocol/docs#33]
Last year in feb there was talk about solana support. I was looking for docs but I can't find any?

**Comment by azf20** [comment]
Hi @sherodtaylor! Solana support is being actively worked on, and will be added to the documentation when it is available for testing. Will update this issue when that is!

**Comment by Web3Slimchance** [comment]
@sherodtaylor See this blogpost for an update on Solana Support via Substreams https://thegraph.com/blog/indexing-solana-substreams/

I also recommend the following resources
 * Substreams [developer guide](https://substreams.streamingfast.io/developer-guide)
 * Substreams [documentation](https://substreams.streamingfast.io/)
 * Substreams Playground on [GitHub](https://github.com/streamingfast/substreams-playground)
 * Chains & Endpoints [documentation](https://substreams.streamingfast.io/reference-and-specs/chains-and-endpoints)
 * Devcon 2022: Introducing The Graph Substreams for High-Performance Indexing [video](https://www.youtube.com/watch?v=K-nhC2FCB5k)
 * Solana SPL Token Transfers Substream [Example Substream](https://github.com/streamingfast/substreams-playground/tree/master/modules/sol-spl-tokens)

**Comment by sherodtaylor** [comment]
@Web3Slimchance this is awesome thanks! 👍
