### ISSUE TITLE
Graphman docs link broken

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/docs#369]
> Small unrelated notes, [the link here to the graphman documentation](https://thegraph.com/docs/en/operating-graph-node/#graphman) and [here](https://thegraph.com/docs/en/operating-graph-node/#configtoml) does not have the .md extension, and therefore is broken, and is also shown as markdown instead of being parsed as an anchor tag
From @YassinEldeeb

**Comment by YassinEldeeb** [comment]
It looks like the markdown links are correctly defined, but probably the client/server side parser has an issue, as it didn’t parse it correctly and parsed a few links without the `.md` extension, even though, they were specified.

https://github.com/graphprotocol/docs/blob/a52086f2e594d72be6029ff2aec1532cbd91ddc0/website/pages/en/operating-graph-node.mdx?plain=1#L275

**Comment by B2o5T** [comment]
@saihaj @YassinEldeeb It was fixed in latest nextra by @enisdenjo, but since these docs is deployed once per month we need to wait next deployment :)

**Comment by azf20** [comment]
@B2o5T which docs deploys once per month? (if you are referring to graphprotocol/docs, we can release more frequently as required 😄 )
