### ISSUE TITLE
substreams modules top level page broken 

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/docs#398]
Clicking on 
![CleanShot 2023-06-01 at 11 31 00@2x](https://github.com/graphprotocol/docs/assets/44710980/b266a609-9c62-4b53-8d16-417f56441626)this page https://thegraph.com/docs/en/substreams/concepts-and-fundamentals/modules/

should take to https://substreams.streamingfast.io/developers-guide/modules

but shows a 403

reported: https://discord.com/channels/438038660412342282/989236488560607262/1113846308067881053

**Comment by B2o5T** [comment]
https://github.com/graphprotocol/docs/blob/eea1e4d1e8bdd9f6e47547071299c10215138e92/website/pages/en/substreams/_meta.js#L19
I filtered this page because I remember it was empty

**Comment by B2o5T** [comment]
@saihaj how this page looks like
<img width="1483" alt="image" src="https://github.com/graphprotocol/docs/assets/7361780/2018592f-97ae-4312-9bba-f85040750b5e">

We should remove/modify links that point to this route.

**Comment by B2o5T** [comment]
@saihaj still empty 🥲 here source code 
https://raw.githubusercontent.com/streamingfast/substreams/develop/docs/developers-guide/modules/README.md

**Comment by saihaj** [comment]
> @saihaj still empty 🥲 here source code 
> 
> https://raw.githubusercontent.com/streamingfast/substreams/develop/docs/developers-guide/modules/README.md
> 
> 
> 
> I think gitbook autogenerate content based on routes

That my makes it complicated now. If we remove then we need to think what happens to the links

**Comment by B2o5T** [comment]
I can create a page with cards like in https://nextra.site/docs/guide or similar component from e&n design system

**Comment by B2o5T** [comment]
or just remove the route from gitbooks too! and all links that points there to overcomplicated things

**Comment by B2o5T** [comment]
or add redirect to another route?

**Comment by saihaj** [comment]
> I can create a page with cards like in https://nextra.site/docs/guide or similar component from e&n design system

Maybe we should create this but we would need an automatic way to figure out how these work 🤔 thoughts @benface

**Comment by B2o5T** [comment]
I think redirecting to substreams’ index page will be simplest way

**Comment by benface** [comment]
Rather, it should redirect to https://thegraph.com/docs/en/substreams/developers-guide/modules/types/, which is the first sub-page of the Developers Guide > Modules section, no?

**Comment by benface** [comment]
@KevinEOSNation – It is still a broken link (403): https://thegraph.com/docs/en/substreams/developers-guide/modules/

It's not clear from @saihaj's OP, but he was referring to the link at the bottom of the https://thegraph.com/docs/en/substreams/concepts-and-fundamentals/modules page, and not that page itself.

**Comment by KevinEOSNation** [comment]
Ah...thank you for the clarification.

**Comment by KevinEOSNation** [comment]
Recommend closing this. SF has revamped its docs and these links now live on https://substreams.streamingfast.io/

@saihaj

**Comment by benface** [comment]
Agreed, closing.
