### ISSUE TITLE
We should add a redirect from `/en/firehose/` to `/en/firehose/README/`. This should ideally be done in 2 places:

### ISSUE THREAD

**Issue by B2o5T** [graphprotocol/docs#406]
We should add a redirect from `/en/firehose/` to `/en/firehose/README/`. This should ideally be done in 2 places:

- In `nginx.conf`, for staging and production
- In `next.config.js`, for local dev with `pnpm dev`

_Originally posted by @benface in https://github.com/graphprotocol/docs/pull/379#discussion_r1220379549_

**Comment by benface** [comment]
Done in #414
