### ISSUE TITLE
pagination problems

### ISSUE THREAD

**Issue by dimaMachina** [graphprotocol/docs#409]
> the “Next” link at the bottom of [this page](https://staging.thegraph.com/docs/en/substreams/getting-started/quickstart/) goes to the wrong page (“Dependency installation”; it skips “Overview”, which is the actual next page).

> Huh, and on the [Dependency installation](https://staging.thegraph.com/docs/en/substreams/developers-guide/installation-requirements/) page, the “Previous” link goes to… the current page. And the “Next” link skips another page, too. (edited)

**Comment by benface** [comment]
@dimaMachina – Any chance you could look into this? 🙏 Here's another example of this issue: https://thegraph.com/docs/en/quick-start/. The previous page is the same as the current one, and the next page skips the following one. It’s like offset by 1 for some reason??
