### ISSUE TITLE
external links broken on the substreams

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/docs#413]
on this page https://thegraph.com/docs/en/substreams/developers-guide/creating-your-manifest/#example-manifest this is a external link but seems to crash

![image](https://github.com/graphprotocol/docs/assets/44710980/2c83a363-02d0-4953-b669-d0c400d2b2d9)

**Comment by B2o5T** [comment]
https://github.com/streamingfast/substreams/pull/230
