### ISSUE TITLE
improving redirects for subitems in docs

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/docs#436]
if you share `https://thegraph.com/docs/en/substreams/developers-guide/modules` it should get redirected to `https://thegraph.com/docs/en/substreams/developers-guide/modules/types/` this way it opens up the first item in the group

![CleanShot 2023-07-03 at 12 14 12@2x](https://github.com/graphprotocol/docs/assets/44710980/0d279273-0ca7-47f6-aa66-441b92d70c08)

thoughts @B2o5T @benface @azf20

**Comment by benface** [comment]
Yes, good idea. Would be nice if we could do this automatically (instead of adding custom redirects in the Next config + nginx.conf for every one of these). 🤔

**Comment by saihaj** [comment]
no longer an issue since we removed mirroring
