### ISSUE TITLE
Search is not available on mobile

### ISSUE THREAD

**Issue by dimaMachina** [graphprotocol/docs#553]
@benface maybe I missed something but I didn’t found a way to search on mobile
![IMG_0253](https://github.com/graphprotocol/docs/assets/7361780/e4a4bc1a-5ceb-4f7f-98f1-48863592bfe8)

**Comment by benface** [comment]
@dimaMachina – It's definitely not intuitive, but the search is in the expandable "navigation":

![IMG_0065](https://github.com/graphprotocol/docs/assets/1059139/fc091039-365c-49c1-a6eb-d59c3be64b19)

**Comment by dimaMachina** [comment]
Oh thanks, should I close this issue?

**Comment by benface** [comment]
Actually no @dimaMachina, you raise a good point and we decided to add a search button to the header on mobile to make it more obvious, I will send a PR for it soon. :)

**Comment by azf20** [comment]
Thanks both! Is this resolved @benface?

**Comment by benface** [comment]
@azf20 – Not yet.
