### ISSUE TITLE
"Query from an application" link is missing

### ISSUE THREAD

**Issue by juanigallo** [graphprotocol/docs#58]
In [https://thegraph.com/docs/en/](https://thegraph.com/docs/en/) the link to "query from an application" is not working.

![image](https://user-images.githubusercontent.com/4969737/153650092-ca7cca58-d53c-4339-a171-f67daa638c66.png)

**Comment by azf20** [comment]
Hi @juanigallo , thanks! Was this an intermittent error? Seems to show up for me 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/9612972/153969401-5a877204-e842-495c-b7fc-68f82bbfcece.png">

**Comment by benface** [comment]
This was fixed in [v1.1.6](https://github.com/graphprotocol/docs/releases/tag/v1.1.6). Thank you!
