### ISSUE TITLE
Amoy wrong chainID on supported networks list page

### ISSUE THREAD

**Issue by jtakalai** [graphprotocol/docs#658]
In this table: https://thegraph.com/docs/en/developing/supported-networks/
Expected: 80002
Found: 8002

Looking at [the code that generates the page](https://github.com/graphprotocol/docs/blob/main/website/src/supportedNetworks.tsx), this value is in a database, and I'm not sure if I can submit a PR for fixing it.

**Comment by yash251** [comment]
Thanks for the flag. We will need to fix from our end.

**Comment by Shiyasmohd** [comment]
This issue has been solved.
