### ISSUE TITLE
wrong link lead to 404 error

### ISSUE THREAD

**Issue by dogcar969** [graphprotocol/docs#667]
In [this article](https://thegraph.com/docs/zh/quick-start/), the link in section four,which text is "创建子图",lead to https://thegraph.com/docs/zh/development/Creating-a-subgraph/ . But the URL of creating subgraph is https://thegraph.com/docs/zh/developing/creating-a-subgraph/

**Comment by benface** [comment]
Thank you, this was a mistake in Crowdin. It will be fixed when #641 is merged and released.
