### ISSUE TITLE
Code snippets in translations have errors

### ISSUE THREAD

**Issue by evaporei** [graphprotocol/docs#72]
After [fixing an issue](https://github.com/graphprotocol/docs/pull/70) we had with the `prettier` formatting in the `AssemblyScript Migration Guide) I realized some code snippets in translations were incorrect.

The issues I've found are listed below:

- [ ] Incorrect compiler messages (eg: [quotes on the wrong place](https://github.com/graphprotocol/docs/blame/d9b858f694e809076c85561b8f99989b3dd0043d/pages/ar/developer/assemblyscript-migration-guide.mdx#L124))
- [ ] Replacing special characters such as `?` to `؟` in code (I couldn't find in the current `main` branch, perhaps this got fixed in the last batch of Crowdin updates? 🤔 )
- [ ] Missing code and comments from the original snippet (eg: [incomplete line](https://github.com/graphprotocol/docs/blame/d9b858f694e809076c85561b8f99989b3dd0043d/pages/ja/developer/assemblyscript-migration-guide.mdx#L277))

**Comment by azf20** [comment]
@evaporei is this issue still active?

**Comment by evaporei** [comment]
I don't think so, I'll close for now.
